### ISSUE TITLE
Open licence

### ISSUE THREAD

**Issue by ChrisBeeley** [sebastian-fox/NHSR_fingertips#1]
This is great! Any chance of an open licence please? 🙏

**Comment by sebastian-fox** [comment]
Hi @ChrisBeeley - I think this is done. If you're happy, please close the issue :)

**Comment by ChrisBeeley** [comment]
Thanks! I'm looking to compile R training for the community and this was an obvious candidate 😊

**Comment by sebastian-fox** [comment]
Great - thank you for including it :)
